version: 2
jobs:
  build:
    working_directory: ~/cci-temp
    docker:
      - image: trenpixster/elixir:1.4.4
      - image: postgres:9.4.1
        environment:
          POSTGRES_USER: ubuntu
    steps:
      - checkout
      - run: mix deps.get
      - run: mix ecto.create
      - run: mix test
