version: 2
jobs:
  build:
    working_directory: ~/cci-temp
    docker:
      - image: trenpixster/elixir:1.4.4
      - image: postgres:9.4.1
        environment:
          POSTGRES_USER: ubuntu
    branches:
      ignore:
        - gh-pages
    steps:
      - checkout
      - run: mix deps.get
      - run: mix ecto.create
      - run: mix test
      - run:
          name: Update Documentation
          shell: /bin/sh
          command: |
              if [ "${CIRCLE_BRANCH}" != "master" ];
                then
                echo "Only build documentation on master branch"
                exit 0;
              fi
              mix docs

              git init
              git config --global user.name "Diego Medina"
              git config --global user.email "diegomedina24@gmail.com"

              git remote add upstream "https://$GH_TOKEN@github.com/OpenFermentor/MonitorBackend.git"
              git fetch upstream && git reset --hard

              git add -f doc/
              git add -f .gitignore
              git reset doc/.build
              git stash
              git clean -fdx
              git rm -rf .
              git stash apply
              git mv doc/* .
              git clean -fdx

              touch .

              git add -A -f .
              git commit -m "Updated documentation"
              git push -f upstream HEAD:gh-pages
